algoritmo "ComparadordeNumerosInteiros"
var
N1, N2: Inteiro

inicio
Escreva("Insira um número: ")
Leia (N1)
Escreva("Insira outro número: ")
Leia (N2)
     Se N1>N2 entao
        Escreva("O Primeiro número é o maior")
     Senao
        Se N1<N2 entao
           Escreva("O segundo numero é maior")
        Senao
           Escreva ("Não existe valor maior, os dois são iguais")
        FimSe
     FimSe




fimalgoritmo
